(() => {
 'use strict';
 const $=id=>document.getElementById(id), M=window.Market, apps=window.APP_DATA, number=new Intl.NumberFormat('en-US'), money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});let page=0;const pageSize=12;
 if(!Array.isArray(apps)||!M){$('selection').textContent='The dataset could not be loaded. Refresh the page or open the linked source repository.';return;}
 const fmt=n=>number.format(n);const filters=()=>({search:$('search').value,category:$('category').value,type:$('type').value,reviews:$('reviews').value});
 [...new Set(apps.map(a=>a.category))].sort().forEach(c=>$('category').add(new Option(M.label(c),c)));
 function bar(parent,label,count,max,category){const row=document.createElement('div');row.className='bar-row';const text=document.createElement(category?'button':'span');text.className='bar-label';text.textContent=label;if(category){text.type='button';text.setAttribute('aria-label',`Filter ${label}, ${fmt(count)} apps`);text.addEventListener('click',()=>{$('category').value=category;page=0;render();});}const track=document.createElement('div');track.className='track';track.setAttribute('aria-hidden','true');const fill=document.createElement('div');fill.className='fill';fill.style.width=(max?count/max*100:0)+'%';track.append(fill);const value=document.createElement('strong');value.textContent=fmt(count);row.append(text,track,value);parent.append(row);}
 function empty(parent,message){const p=document.createElement('p');p.className='empty';p.textContent=message;parent.append(p);}
 function render(){const selected=M.filterApps(apps,filters()),s=M.summarize(selected),sorted=M.sortApps(selected,$('sort').value),pages=Math.max(1,Math.ceil(s.count/pageSize));page=Math.min(page,pages-1);
 $('selection').textContent=`${fmt(s.count)} of ${fmt(apps.length)} apps match your filters.`;$('count').textContent=fmt(s.count);$('share').textContent=(s.count/apps.length*100).toFixed(1)+'% of the source sample';$('rating').textContent=s.mean===null?'—':s.mean.toFixed(2);$('rated').textContent=`${fmt(s.rated)} rated apps · out of 5`;$('free').textContent=s.count?(s.free/s.count*100).toFixed(1)+'%':'—';$('free-count').textContent=`${fmt(s.free)} free apps in view`;$('price').textContent=s.median===null?'—':money.format(s.median);$('paid-count').textContent=`${fmt(s.paid)} paid apps · USD`;
 $('categories').replaceChildren();const cats=M.categoryCounts(selected).slice(0,8);if(!cats.length)empty($('categories'),'No apps match. Try fewer filters.');cats.forEach(([c,n])=>bar($('categories'),M.label(c),n,cats[0][1],c));
 $('distribution').replaceChildren();const bins=M.ratingBins(selected);if(!s.rated)empty($('distribution'),'No rated apps in this selection.');else bins.forEach((n,i)=>bar($('distribution'),['1–<2','2–<3','3–<4','4–<5','Exactly 5'][i],n,Math.max(...bins)));$('rating-note').textContent=`${fmt(s.count-s.rated)} apps have no rating and are excluded above.`;
 $('rows').replaceChildren();sorted.slice(page*pageSize,(page+1)*pageSize).forEach(a=>{const tr=document.createElement('tr');[a.name,M.label(a.category),a.rating===null?'Not rated':a.rating.toFixed(1),fmt(a.reviews),a.installs,a.type==='Free'?'Free':money.format(a.price)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});$('rows').append(tr);});if(!s.count){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.textContent='No apps found. Reset filters to explore the full sample.';tr.append(td);$('rows').append(tr);}
 $('page-info').textContent=s.count?`${fmt(page*pageSize+1)}–${fmt(Math.min((page+1)*pageSize,s.count))} of ${fmt(s.count)}`:'0 results';$('previous').disabled=page===0;$('next').disabled=page>=pages-1;
 }
 $('filters').addEventListener('submit',e=>e.preventDefault());$('filters').addEventListener('input',()=>{page=0;render();});$('sort').addEventListener('change',()=>{page=0;render();});$('reset').addEventListener('click',()=>{$('filters').reset();$('sort').value='reviews';page=0;render();});$('previous').addEventListener('click',()=>{page--;render();});$('next').addEventListener('click',()=>{page++;render();});render();
})();
